server:
  port: 8082

spring:
  application:
    name: TRANSACTIONS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transactions?createDatabaseIfNotExist=true
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
